# -*- coding: utf-8 -*-
"""image processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EftZgh8w6WnQbNO5A6S1jFiJnii5AQVE

Image processing

Apply ImageDataGenerator Functionality To Train And Test Set
"""

#import imagedatagenerator
from keras.preprocessing.image import ImageDataGenerator

#training datagen
train_datagen=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)

#testing datagen
test_datagen=ImageDataGenerator(rescale=1./255)

"""IMPORTING tensorflow"""

import tensorflow as tf
import os

"""IMPORTING SEQUENTIAL, DENSE, FLATTEN LAYER"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import numpy as np
import matplotlib.pyplot as plt #to view graph in colab itself
import IPython.display as display
from PIL import Image
import pathlib

"""Unzipping the dataset"""

!unzip '/content/conversation engine for deaf and dumb (1).zip'