# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X5nLIDtOgqFHPA7lHMC3hfMDgbvny6J0

1.split this string

2.use.format() to print the following string.
output should be:the diameter of earth is 12742 kilometers.
"""

planet="earth"
diameter=12742
planet="earth"
diameter=12742
print('the diameter of earth {}is 12742 kilometers')

"""3.in this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d = {
  'k1': [1, 2, 3, {
    'tricky': ['oh', 'man', 'inception', {
      'target': [1, 2, 3, 'hello']
    }]
  }]
}

s="hi there surya!"
string="hi there surya!"
print(string.split())

"""nam

4.numpy
"""

import numpy as np

"""4.1 create an array of 10 zeros?
4.2 create an array of 10 fives?
"""

import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

"""5. Create an array of all the even integers from 20 to 35"""

import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

"""6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

"""7. Concatenate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.concatenate((a, b))

"""pandas

8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

# Import pandas library
import pandas as pd

# initialize list of lists
data = [['tom', 10], ['nick', 15]]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])

# print dataframe.
df

"""9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

# importing pandas as pd
import pandas as pd

per1 = pd.date_range(start ='1-1-2023',
		end ='10-02-2023', freq ='6H')

for val in per1:
	print(val)

"""10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
"""

# Import pandas library
import pandas as pd

# initialize list of lists
data = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24] ]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['Category', 'Name', 'Marks'])

# print dataframe.
print(df )